# Generated by Django 4.0.6 on 2022-08-05 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=64)),
                ('opis', models.TextField()),
                ('kategoria', models.CharField(choices=[('osobowy', 'Osobowy'), ('motocykl', 'Motocykl'), ('ciezarowy', 'Ciężarowy')], default='osobowy', max_length=16)),
                ('marka', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('rok_produkcji', models.IntegerField()),
                ('przebieg', models.IntegerField()),
                ('pojemnosc_skokowa', models.IntegerField()),
                ('moc', models.IntegerField()),
                ('paliwo', models.CharField(choices=[('pb', 'Benzyna'), ('on', 'Diesel'), ('lpg', 'LPG')], max_length=8)),
                ('zdjecie', models.ImageField(null=True, upload_to='images/')),
                ('data_dodania', models.DateField()),
                ('data_publikacji', models.DateField(blank=True, null=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
