# Generated by Django 4.0.6 on 2022-08-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0002_alter_oferta_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='data_publikacji',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='opis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='zdjecie',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
