# Generated by Django 4.0.6 on 2022-08-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0003_alter_offer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='placeholder.png', null=True, upload_to='images/'),
        ),
    ]
