# Generated by Django 4.0.6 on 2022-08-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoSell', '0004_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='images/'),
        ),
    ]
